pom.xml, scripts/aws/cfn/microservice.yml, scripts/aws/cfn/storage.yml, src/main/java/it/pagopa/pn/radd/mapper/TransactionDataMapper.java, src/main/java/it/pagopa/pn/radd/middleware/db/RaddTransactionDAO.java, src/main/java/it/pagopa/pn/radd/middleware/db/entities/OperationsIunsEntity.java, src/main/java/it/pagopa/pn/radd/middleware/db/entities/RaddTransactionEntity.java, src/main/java/it/pagopa/pn/radd/middleware/db/impl/OperationsIunsDAOImpl.java, src/main/java/it/pagopa/pn/radd/middleware/db/impl/RaddTransactionDAOImpl.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/BaseService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/OperationService.java, src/test/java/it/pagopa/pn/radd/middleware/db/OperationsIunsDAOImplTest.java, src/test/java/it/pagopa/pn/radd/middleware/db/RaddTransactionDAOImplTest.java, src/test/java/it/pagopa/pn/radd/middleware/db/RaddTransactionDAOTestIT.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActServiceStartTransactionTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActServiceTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorServiceTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/OperationServiceTest.java
Updated dependency of commons pn modules in pom.xml.
Changed project and entities name in cloudformation.
=> PN-9664 refactor: entities and methods to retrieve them

src/main/java/it/pagopa/pn/radd/rest/radd/fsu/AorPrivateRestV1Controller.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorService.java, src/test/java/it/pagopa/pn/radd/rest/radd/fsu/AorPrivateRestV1ControllerTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorServiceTest.java
Added parameters cxType and cxId in abortTransaction
=> Work Item 2.4 PN-9676 - aorDocumentInquiry - abort

src/main/java/it/pagopa/pn/radd/rest/radd/fsu/ActPrivateRestV1Controller.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActService.java, src/test/java/it/pagopa/pn/radd/rest/radd/fsu/ActPrivateRestV1ControllerTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActServiceTest.java
feature: added cxType and xcId in actInquiry - abort
=> Work item 1.4 - Modifica logica actTransactionManagement - abort

config/application-test.properties, src/main/java/it/pagopa/pn/radd/middleware/db/entities/OperationsIunsEntity.java, src/test/resources/testcontainers/init.sh
Fixed table names cloud formation
=> Fixed table names

src/main/java/it/pagopa/pn/radd/mapper/TransactionDataMapper.java
added field to method toEntity
=> Fix method toEntity

src/main/java/it/pagopa/pn/radd/middleware/msclient/PnDataVaultClient.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/DocumentOperationsService.java
Updated method documentDownload
=> Fix documentDownload Method

scripts/aws/cfn/storage.yml
Updated OperationsDynamoTable: added iun as sort key
=> Fix Cloud Formation

src/main/java/it/pagopa/pn/radd/middleware/db/RaddTransactionDAO.java, src/main/java/it/pagopa/pn/radd/middleware/db/impl/RaddTransactionDAOImpl.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActService.java, src/test/java/it/pagopa/pn/radd/mapper/ActInquiryResponseMapperTest.java, src/test/java/it/pagopa/pn/radd/mapper/StartTransactionResponseMapperTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActServiceStartTransactionTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActServiceTest.java
FIX: added recipientId to checkIun query
=> Fix Added recipientId to checkIun query

docs/postman/pn-radd-alt.postman_environment.json, docs/postman/radd-alt.postman_collection.json
Added postman-collection and postman-environment
=> Added Postman Collection

docs/openapi/aws/api-radd-net-RADD-aws.yaml, docs/openapi/pn-radd-alt-external.yaml, docs/openapi/pn-radd-alt-internal.yaml
Aggiunta definizione per lo swagger delle api in linguaggio markdown
=> aggiornamentoSwagger inserita definizione

scripts/aws/cfn/microservice.yml, scripts/aws/cfn/storage.yml, src/main/java/it/pagopa/pn/radd/config/PnRaddFsuConfig.java, src/test/resources/testcontainers/init.sh
Added queue pn-radd-alt-internal-cap-checker in init.sh for localstack
=> [PN-10469] Feat: Added queue pn-radd-alt-internal-cap-checker resource

docs/openapi/pn-radd-alt-import-registry-internal.yaml, docs/openapi/pn-radd-alt-registry-internal.yaml, docs/openapi/schemas-pn-radd-alt-registry.yaml, src/main/java/it/pagopa/pn/radd/exception/ExceptionTypeEnum.java, src/main/java/it/pagopa/pn/radd/mapper/RaddRegistryRequestEntityMapper.java, src/main/java/it/pagopa/pn/radd/middleware/db/impl/RaddRegistryRequestDAOImpl.java, src/main/java/it/pagopa/pn/radd/middleware/queue/consumer/handler/InternalCapCheckerEventHandler.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/RegistryImportProgressService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/RegistrySelfService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/RegistryService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/SafeStorageEventService.java, src/main/java/it/pagopa/pn/radd/utils/Const.java, src/main/java/it/pagopa/pn/radd/utils/RaddRegistryUtils.java, src/main/java/it/pagopa/pn/radd/utils/Utils.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/RegistrySelfServiceTest.java
=> added validation to create and update registry api

scripts/aws/cfn/storage.yml
=> Fix: increased visibility timeout of pn-radd_alt_input to 3 min

src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorService.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorServiceTest.java
PN-10625 fix: fixed auditLog in abortTransactionAOR and fixed jUnit test logAssertions
=> PN-10625 fix: fixed auditLog in abortTransactionAOR

src/main/java/it/pagopa/pn/radd/config/RestExceptionHandler.java, src/main/java/it/pagopa/pn/radd/exception/PnRaddForbiddenException.java, src/main/java/it/pagopa/pn/radd/rest/radd/fsu/DocumentOperationsRestV1Controller.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/DocumentOperationsService.java, src/main/java/it/pagopa/pn/radd/utils/RaddRole.java, src/test/java/it/pagopa/pn/radd/rest/radd/fsu/DocumentOperationsRestV1ControllerTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/DocumentOperationsServiceTest.java
Added header role and checkRole in DocumentOperations
=> PN-11843 feature: Added header role and checkRole in DocumentOperations

docs/openapi/pn-radd-alt-registry-internal.yaml, src/main/java/it/pagopa/pn/radd/config/RestExceptionHandler.java, src/main/java/it/pagopa/pn/radd/mapper/RaddRegistryRequestEntityMapper.java, src/main/java/it/pagopa/pn/radd/utils/Const.java, src/test/java/it/pagopa/pn/radd/rest/radd/fsu/RegistrySelfControllerTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/CsvServiceTest.java, src/test/resources/radd-registry.csv
Added mandatory control for description and phone number, also added the validation of the phone number format.
=> [PN-11847] Feat: Added validation for parameters description and phone number.

docs/openapi/pn-radd-alt-external.yaml, docs/openapi/pn-radd-alt-internal.yaml
Added description for new document "autodichiarazione" in openApi.
=> [PN-12081] Feat: Added description for new document "autodichiarazione" in openApi.

docs/openapi/pn-radd-alt-internal.yaml
feature/PN-11931: changed open api and removed comment with no-external
=> feature/PN-11931: changed open api and removed comment with no-external

docs/openapi/aws/api-radd-net-RADD-aws.yaml, docs/openapi/pn-radd-alt-external.yaml, docs/openapi/pn-radd-alt-internal.yaml, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorService.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/BaseService.java, src/main/java/it/pagopa/pn/radd/utils/Const.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActServiceTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/AorServiceTest.java
[PN-12568] feat: Removed mandatory versionToken
[PN-12568]: https://pagopa.atlassian.net/browse/PN-12568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12568] feat: Removed mandatory versionToken

src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/BaseService.java
[PN-12852] Fix empty string fileKey
[PN-12852]: https://pagopa.atlassian.net/browse/PN-12852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12852] Fix empty string fileKey

src/main/java/it/pagopa/pn/radd/mapper/RegistryMappingUtils.java, src/main/java/it/pagopa/pn/radd/middleware/db/BaseDao.java, src/main/java/it/pagopa/pn/radd/middleware/db/RaddRegistryV2DAO.java, src/main/java/it/pagopa/pn/radd/middleware/db/impl/RaddRegistryV2DAOImpl.java, src/main/java/it/pagopa/pn/radd/rest/radd/fsu/RegistrySelfController.java, src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/RegistrySelfService.java, src/main/java/it/pagopa/pn/radd/utils/RaddRegistryUtils.java, src/test/java/it/pagopa/pn/radd/mapper/RegistryMappingUtilsTest.java, src/test/java/it/pagopa/pn/radd/middleware/db/RaddRegistryV2DAOImplTest.java, src/test/java/it/pagopa/pn/radd/middleware/msclient/PnAddressManagerClientTest.java, src/test/java/it/pagopa/pn/radd/rest/radd/fsu/RegistrySelfControllerTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/RegistrySelfServiceTest.java, src/test/java/it/pagopa/pn/radd/services/radd/fsu/v1/RegistryServiceTest.java, src/test/java/it/pagopa/pn/radd/utils/RaddRegistryUtilsTest.java
- Added new DAO in v2 for filtering
- Introduced new filterExpression for raddRegistryV2
- Updated registry mapping
- Commented tests in PnAddressManagerClientTest
=> PN-16374: update registry listing and tests
